name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Run linter (ruff)
        run: |
          uv run ruff check src/ --fix

      - name: Run code formatter (ruff)
        run: |
          uv run ruff format src/ --check

      - name: Run tests
        run: |
          uv run pytest src/ || echo "No tests found - this is expected for a student project"
